# render.yaml

services:
  # A name for your web service
  - name: med-chatbot
    # The type of service
    type: web
    # The environment (e.g., Python, Node)
    env: python
    # Specify the free plan
    plan: free
    # The command to install dependencies
    buildCommand: "pip install -r requirements.txt"
    # The command to start your application
    startCommand: "gunicorn app:app"
