# .github/workflows/medical_chatbot_ci.yml

name: Medical Chatbot CI/CD

# This workflow runs on pushes or pull requests to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the specific version of Python your project uses
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Cache dependencies to speed up future builds
      # The key now uses the hardcoded Python version to avoid linter warnings.
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-3.11-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-3.11-pip-

      # Step 4: Install the project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 5: Lint code with flake8 to check for style issues and errors
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics


      # Step 6: Run tests with pytest
      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest